import os

import streamlit as st

from pawpal_agent import plan_care

st.set_page_config(page_title="PawPal+", page_icon="🐾", layout="centered")

st.title("🐾 PawPal+")
st.write("Plan your pet's daily care schedule based on priorities and available time.")

# -------------------------
# Owner & Pet Information
# -------------------------
st.header("Owner & Pet Information")

owner_name = st.text_input("Owner Name", value="Jordan")
pet_name = st.text_input("Pet Name", value="Mochi")
species = st.selectbox("Species", ["Dog", "Cat", "Other"])
available_time = st.number_input(
    "Available Time (minutes)",
    min_value=15,
    max_value=480,
    value=90,
)

st.divider()

# -------------------------
# Task Input
# -------------------------
st.header("Add Pet Care Tasks")

if "tasks" not in st.session_state:
    st.session_state.tasks = []

col1, col2, col3 = st.columns(3)

with col1:
    task_title = st.text_input("Task Title", value="Morning Walk")

with col2:
    duration = st.number_input(
        "Duration (minutes)",
        min_value=1,
        max_value=240,
        value=20,
    )

with col3:
    priority = st.selectbox(
        "Priority",
        ["high", "medium", "low"],
    )

recurring = st.checkbox("Recurring Task")

if st.button("Add Task"):
    st.session_state.tasks.append(
        {
            "title": task_title,
            "duration": int(duration),
            "priority": priority,
            "recurring": recurring,
        }
    )
    st.success(f"Added '{task_title}'.")

if st.session_state.tasks:
    st.subheader("Current Tasks")

    header = st.columns([3, 2, 2, 2, 1])
    header[0].markdown("**Task**")
    header[1].markdown("**Duration**")
    header[2].markdown("**Priority**")
    header[3].markdown("**Recurring**")
    header[4].markdown("**Remove**")

    for i, item in enumerate(st.session_state.tasks):
        row = st.columns([3, 2, 2, 2, 1])
        row[0].write(item["title"])
        row[1].write(f"{item['duration']} min")
        row[2].write(item["priority"].title())
        row[3].write("Yes" if item.get("recurring") else "No")
        if row[4].button("🗑️", key=f"del_{i}", help=f"Remove '{item['title']}'"):
            st.session_state.tasks.pop(i)
            st.rerun()

    if st.button("Clear All Tasks"):
        st.session_state.tasks = []
        st.rerun()
else:
    st.info("No tasks added yet.")

st.divider()

# -------------------------
# Generate Schedule
# -------------------------
st.header("Daily Schedule")

# The agent uses the live Claude loop only when an API key is present; otherwise
# it falls back to the deterministic scheduler. Surface which path will run so
# the UI is honest about what the user is seeing.
if os.environ.get("ANTHROPIC_API_KEY"):
    st.caption("🤖 AI Care Planner active (Claude agent).")
else:
    st.caption(
        "⚠️ No `ANTHROPIC_API_KEY` set — using the deterministic fallback planner "
        "(safe baseline, no AI)."
    )

if st.button("Generate Schedule"):

    if not st.session_state.tasks:
        st.warning("Add at least one task before generating a schedule.")
        st.stop()

    # Map the UI task shape onto the keys the agent/guardrails expect.
    agent_tasks = [
        {
            "title": item["title"],
            "duration_minutes": int(item["duration"]),
            "priority": item["priority"],
            "recurring": item.get("recurring", False),
        }
        for item in st.session_state.tasks
    ]

    # Guardrail: invalid input (bad duration/priority/etc.) is rejected before
    # any AI call. Show the message instead of crashing the app.
    try:
        with st.spinner("Planning the day…"):
            result = plan_care(int(available_time), agent_tasks)
    except ValueError as exc:
        st.error(f"Could not build a plan: {exc}")
        st.stop()

    engine = f"Claude agent ({result.model})" if result.used_llm else "deterministic fallback"
    st.success(f"Schedule generated by the {engine}.")

    # -------- Reliability signals: confidence + risk flags --------
    conf_col, turns_col, time_col = st.columns(3)
    conf_col.metric("Confidence", f"{result.confidence:.2f}")
    turns_col.metric("Agent turns", result.iterations)
    time_col.metric(
        "Time Used",
        f"{result.time_used} / {result.available_time} min",
    )

    if result.health_risk_flags:
        st.error("**Health risk flags:**\n" + "\n".join(f"- {f}" for f in result.health_risk_flags))

    st.subheader("Scheduled Tasks")
    if result.scheduled:
        for title in result.scheduled:
            st.markdown(f"✅ **{title}**")
    else:
        st.warning("No tasks could be scheduled.")

    if result.skipped:
        st.subheader("Skipped Tasks")
        for title in result.skipped:
            st.markdown(f"❌ {title}")

    st.subheader("AI Explanation")
    st.write(result.explanation)

    with st.expander("Why this confidence score?"):
        for reason in result.confidence_reasons:
            st.markdown(f"- {reason}")

    if result.conflicts:
        st.warning("Some tasks could not be scheduled due to limited available time.")
    else:
        st.success("All tasks fit within the available time.")